using Solution.Answers;

HasPathSum.Run();
//LetterCombinations.Run();
//StringtoIntegerAtoi.Run();
//SudokuSolver.Run();
//ThreeSum.Run();
//IntegerToRoman.Run();
//ZigzagConversion.Run();
//LongestSubstringWithoutRepeatingCharacters.Run();
//ThreeDigitLock.Run();
//PlusOne.Run();
//MaximumSubarray.Run();
//ValidParentheses.Run();
//LongestPalindromicSubstring.Run();
//ImplementStrStr.Run();
//ReverseInteger.Run();
//RemoveDuplicatesFromSortedArray.Run();
//LongestCommonPrefix.Run();
//PalindromeNumber.Run();
//MergeTwoSortedLists.Run();
//AddTwoNumbers.Run();
//RomantoInteger.Run();
//TwoSum.Run();
